apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ikijjmdwj-nodejs 
  janus-idp.io/tekton: ikijjmdwj-nodejs
  backstage.io/kubernetes-id: ikijjmdwj-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ikijjmdwj-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml